set -g default-terminal "xterm-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

# shift + alt + H and shift + alt + L to move between windows
bind -n M-H previous-window
bind -n M-L next-window
bind r source-file ~/.config/tmux/tmux.conf

# Start numbering windows from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g set-clipboard on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

# Optional: make copy/paste friendlier
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send -X rectangle-toggle

bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

run '~/.tmux/plugins/tpm/tpm'
run '~/.config/tmux/theme.tmux'

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set-window-option -g automatic-rename off
set-option -g allow-rename off

# Enable vi key bindings in copy mode
# set -g mode-keys vi

# Use vi keys in command prompt too
# set -g status-keys vi

# set vi-mode
set-window-option -g mode-keys vi
