# ~/.config/starship.toml
palette = 'catppuccin'
format = '''$directory$git_branch$git_state$git_status$fill$all$character'''

[palettes.catppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"

[character]
format = "$symbol($style) "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[](bold blue)"
vimcmd_replace_one_symbol = "[](bold red)"
vimcmd_replace_symbol = "[](bold red)"
vimcmd_visual_symbol = "[](bold mauve)"


[docker_context]
disabled = false

[conda]
disabled = false
format = 'via [$symbol$environment]($style) '

[cmd_duration]
disabled = false
min_time = 1

[fill]
symbol = " "

[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
style = "bold green"
read_only = "  "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold yellow"

[git_status]
format = "$all_status($style) "

conflicted = "[ conflicted ](bold red)"  
ahead = "[ ahead ${count} ](bold yellow)"        
behind = "[ behind ${count}](bold mauve)"      
untracked = "[ untracked ](bold blue)"
stashed = "[ stashed ](bold sky)"    
modified = "[ modified ](bold peach)"
staged = "[ staged ](bold green)"   
renamed = "[» renamed ](bold lavender)"
deleted = "[✘ deleted ](bold red)"    
diverged = '[ diverged ${ahead_count} ${behind_count}](bold red)'

[git_state]
disabled = false
format = '\([$state( [$progress_current/$progress_total](bold green))]($style)\) '

[time]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[python]
disabled = true

[lua]
disabled = true
