# Advanced
shell zsh
editor nvim
close_on_child_death no
allow_remote_control socket-only
listen_on unix:/tmp/kitty
update_check_interval 24
startup_session none
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
clipboard_max_size 64
allow_hyperlinks yes
shell_integration enabled
allow_cloning ask
clone_source_strategies venv,conda,env_var,path
term xterm-kitty
